FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package.json ./package.json
RUN npm install

COPY frontend/ ./

ARG VITE_IDENTITY_API_URL=http://localhost:8001
ARG VITE_CUSTOMER_API_URL=http://localhost:8002
ARG VITE_CATALOG_API_URL=http://localhost:8003
ARG VITE_INVENTORY_API_URL=http://localhost:8004
ARG VITE_PRICING_API_URL=http://localhost:8005
ARG VITE_CART_API_URL=http://localhost:8006
ARG VITE_ORDER_API_URL=http://localhost:8007
ARG VITE_PAYMENT_API_URL=http://localhost:8008
ARG VITE_SHIPPING_API_URL=http://localhost:8009
ARG VITE_SEARCH_API_URL=http://localhost:8010
ARG VITE_RECOMMENDATION_API_URL=http://localhost:8011
ARG VITE_REVIEW_API_URL=http://localhost:8012
ARG VITE_NOTIFICATION_API_URL=http://localhost:8013
ARG VITE_RETURN_REFUND_API_URL=http://localhost:8014
ARG VITE_ANALYTICS_API_URL=http://localhost:8015
ARG VITE_BACKOFFICE_API_URL=http://localhost:8016

ENV VITE_IDENTITY_API_URL=${VITE_IDENTITY_API_URL}
ENV VITE_CUSTOMER_API_URL=${VITE_CUSTOMER_API_URL}
ENV VITE_CATALOG_API_URL=${VITE_CATALOG_API_URL}
ENV VITE_INVENTORY_API_URL=${VITE_INVENTORY_API_URL}
ENV VITE_PRICING_API_URL=${VITE_PRICING_API_URL}
ENV VITE_CART_API_URL=${VITE_CART_API_URL}
ENV VITE_ORDER_API_URL=${VITE_ORDER_API_URL}
ENV VITE_PAYMENT_API_URL=${VITE_PAYMENT_API_URL}
ENV VITE_SHIPPING_API_URL=${VITE_SHIPPING_API_URL}
ENV VITE_SEARCH_API_URL=${VITE_SEARCH_API_URL}
ENV VITE_RECOMMENDATION_API_URL=${VITE_RECOMMENDATION_API_URL}
ENV VITE_REVIEW_API_URL=${VITE_REVIEW_API_URL}
ENV VITE_NOTIFICATION_API_URL=${VITE_NOTIFICATION_API_URL}
ENV VITE_RETURN_REFUND_API_URL=${VITE_RETURN_REFUND_API_URL}
ENV VITE_ANALYTICS_API_URL=${VITE_ANALYTICS_API_URL}
ENV VITE_BACKOFFICE_API_URL=${VITE_BACKOFFICE_API_URL}

RUN npm run build

FROM nginx:1.27-alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
